# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 ViralMint Contributors
"""AI + heuristic storyboard planner for long-form videos."""
from __future__ import annotations

import json
import logging
import math
from typing import Optional
from uuid import uuid4

from backend.core.ai_provider import AIClient, get_ai_client
from backend.services.prompt_synth_service import _safe_json_load, translate_narrative_to_english_keywords

logger = logging.getLogger(__name__)

SCENE_TYPES_NEED_RENDER = {"ltx", "stock", "user_video", "kenburns", "user_image", "screenshot"}
LTX_TYPES = {"ltx"}
MIN_SCENE_S = 4.0
MAX_KENBURNS_STREAK = 1
MAX_LTX_SCENE_S = 10.0


def _scene_duration(scene: dict) -> float:
    return max(0.1, float(scene["end_s"]) - float(scene["start_s"]))


def _needs_gpu(scene_type: str) -> bool:
    return scene_type == "ltx"


def _render_status_for_type(scene_type: str) -> str:
    if scene_type in ("user_image", "screenshot"):
        return "pending"  # ken burns on generate
    if scene_type == "ltx":
        return "pending"
    if scene_type == "stock":
        return "pending"
    if scene_type == "user_video":
        return "pending"
    if scene_type == "kenburns":
        return "pending"
    return "pending"


def _visual_status_for_type(scene_type: str, preview_url: str | None) -> str:
    if scene_type == "ltx":
        return "placeholder" if not preview_url else "preview_ready"
    return "preview_ready" if preview_url else "placeholder"


async def plan_storyboard(
    topic: str,
    narrative_blocks: list[dict],
    assets: list[dict],
    total_duration_s: float,
    aspect_ratio: str = "9:16",
    ltx_ratio: float = 0.45,
    max_ltx_scene_s: float = MAX_LTX_SCENE_S,
    user_id: str = "local",
) -> dict:
    """Build storyboard from narrative blocks + asset catalog."""
    ai_client: Optional[AIClient] = None
    try:
        from sqlalchemy import select
        from backend.database import AsyncSessionLocal
        from backend.models.user_settings import UserSettings
        async with AsyncSessionLocal() as db:
            r = await db.execute(select(UserSettings).where(UserSettings.user_id == user_id))
            user_settings = r.scalar_one_or_none()
        ai_client = get_ai_client(user_settings)
    except Exception:
        pass

    english_keywords = await translate_narrative_to_english_keywords(
        topic, narrative_blocks, ai_client,
    )

    if ai_client and narrative_blocks:
        try:
            board = await _plan_with_ai(
                ai_client, topic, narrative_blocks, assets,
                total_duration_s, aspect_ratio, ltx_ratio, max_ltx_scene_s,
                english_keywords,
            )
            if board.get("scenes"):
                board["scenes"] = postprocess_scenes(
                    board["scenes"], topic, narrative_blocks, english_keywords,
                    total_duration_s,
                )
                return _enrich_scenes(board, assets, total_duration_s, aspect_ratio, topic)
        except Exception as e:
            logger.warning("DEBUG:: AI storyboard failed, using heuristic: %s", e)

    board = _plan_heuristic(
        topic, narrative_blocks, assets, total_duration_s,
        aspect_ratio, ltx_ratio, max_ltx_scene_s, english_keywords,
    )
    board["scenes"] = postprocess_scenes(
        board["scenes"], topic, narrative_blocks, english_keywords,
        total_duration_s,
    )
    return _enrich_scenes(board, assets, total_duration_s, aspect_ratio, topic)


async def _plan_with_ai(
    ai_client: AIClient,
    topic: str,
    blocks: list[dict],
    assets: list[dict],
    total_duration_s: float,
    aspect_ratio: str,
    ltx_ratio: float,
    max_ltx_scene_s: float,
    english_keywords: list[str] | None = None,
) -> dict:
    asset_summary = [
        {
            "id": a["id"],
            "kind": a.get("kind"),
            "description": (a.get("catalog") or {}).get("description", ""),
            "detected_type": (a.get("catalog") or {}).get("detected_type", ""),
            "suggested_use": (a.get("catalog") or {}).get("suggested_use", ""),
        }
        for a in assets
    ]
    prompt = f"""Plan a video storyboard as JSON for topic: {topic}
Total audio duration: {total_duration_s:.1f}s. Aspect: {aspect_ratio}.
Target ~{int(ltx_ratio * 100)}% LTX scenes (type "ltx"), max {max_ltx_scene_s}s each (hard limit — never longer).

IMPORTANT rules for scene types:
- user_image / screenshot / user_video / kenburns: use ONLY the user's uploaded assets (asset_id).
- stock: Pexels video B-roll (source.query).
- ltx: motion B-roll generated by AI video model from a STOCK PHOTO start frame + audio slice.
  NEVER set start_image_asset_id on ltx scenes — do NOT use user portraits or screenshots for LTX
  (lip-sync on real photos looks wrong). Instead set source.stock_image_query to a Pexels photo
  search (e.g. "cinematic students studying library", "exam hall atmosphere", "celebration confetti").
  Also set source.prompt describing camera motion (slow pan, ambient movement) NOT lip-sync.
- ALL source.query and source.stock_image_query values MUST be English only (for Pexels search).
- Put original narration language in transcript; use visual_keywords_en for English B-roll keywords.

English keywords per block (use these for stock/LTX queries): {json.dumps(english_keywords or [])}

Assets: {json.dumps(asset_summary)}
Narrative blocks: {json.dumps(blocks)}

Return JSON:
{{"scenes": [{{"start_s": 0, "end_s": 8, "type": "kenburns|user_image|user_video|screenshot|stock|ltx",
"source": {{}}, "transcript": "...", "narration_hint": "...", "visual_keywords_en": "english b-roll keywords"}}]}}
Scene times must cover 0 to {total_duration_s} with no gaps. No scene shorter than {MIN_SCENE_S}s.
No ltx scene longer than {max_ltx_scene_s}s. Avoid more than one consecutive kenburns scene."""
    resp = await ai_client.chat(
        [{"role": "user", "content": prompt}],
        max_tokens=4000,
    )
    data = _safe_json_load(resp)
    return {
        "topic": topic,
        "total_duration_s": total_duration_s,
        "aspect_ratio": aspect_ratio,
        "scenes": data.get("scenes", []),
    }


def _plan_heuristic(
    topic: str,
    blocks: list[dict],
    assets: list[dict],
    total_duration_s: float,
    aspect_ratio: str,
    ltx_ratio: float,
    max_ltx_scene_s: float,
    english_keywords: list[str] | None = None,
) -> dict:
    images = [a for a in assets if a.get("kind") == "image"]
    videos = [a for a in assets if a.get("kind") == "video"]
    ltx_budget = total_duration_s * ltx_ratio
    ltx_used = 0.0
    img_i = vid_i = 0
    scenes = []
    idx = 1

    for i, block in enumerate(blocks or [{"start_s": 0, "end_s": total_duration_s, "text": topic}]):
        start = float(block["start_s"])
        block_end = float(block["end_s"])
        dur = block_end - start
        if dur < 0.5:
            continue
        text = block.get("text", "")
        en_kw = english_keywords[i] if english_keywords and i < len(english_keywords) else topic
        stype = "stock"
        source: dict = {"query": en_kw}
        scene_end = block_end

        if videos and vid_i < len(videos) and dur >= 5:
            asset = videos[vid_i]
            vid_i += 1
            stype = "user_video"
            source = {"asset_id": asset["id"], "trim_in_s": 0, "trim_out_s": min(dur, (asset.get("catalog") or {}).get("duration_s") or dur)}
        elif images and img_i < len(images):
            asset = images[img_i]
            cat = asset.get("catalog") or {}
            det = cat.get("detected_type", "")
            if det == "screenshot":
                stype = "screenshot"
                source = {"asset_id": asset["id"], "motion": "slow_zoom_in"}
            elif dur >= 12:
                stype = "user_image"
                img_i += 1
                source = {"asset_id": asset["id"], "motion": "slow_pan"}
            elif dur >= MIN_SCENE_S:
                stype = "kenburns"
                source = {"asset_id": asset["id"], "motion": "slow_zoom_in"}
            else:
                stype = "stock"
                source = {"query": en_kw}
        elif ltx_used + min(dur, max_ltx_scene_s) <= ltx_budget and dur >= MIN_SCENE_S:
            ltx_dur = min(dur, max_ltx_scene_s)
            stype = "ltx"
            scene_end = start + ltx_dur
            source = {
                "stock_image_query": ltx_stock_image_query(topic, en_kw),
                "prompt": f"Slow cinematic camera movement, ambient B-roll motion, no lip sync. Context: {en_kw}",
            }
            ltx_used += ltx_dur

        scenes.append({
            "id": f"s{idx}",
            "start_s": round(start, 2),
            "end_s": round(scene_end, 2),
            "type": stype,
            "source": source,
            "transcript": text,
            "narration_hint": text[:120] or topic,
            "visual_keywords_en": en_kw,
        })
        idx += 1

        if stype == "ltx" and scene_end < block_end - 0.5:
            scenes.append({
                "id": f"s{idx}",
                "start_s": round(scene_end, 2),
                "end_s": round(block_end, 2),
                "type": "stock",
                "source": {"query": en_kw},
                "transcript": text,
                "narration_hint": text[:120] or topic,
                "visual_keywords_en": en_kw,
            })
            idx += 1

    _normalize_scene_coverage(scenes, total_duration_s)
    return {
        "topic": topic,
        "total_duration_s": total_duration_s,
        "aspect_ratio": aspect_ratio,
        "scenes": scenes,
    }


def _stock_query(topic: str, text: str, english_kw: str | None = None) -> str:
    if english_kw:
        return english_kw
    words = (text or topic).split()
    meaningful = [w for w in words if len(w) > 3][:4]
    return " ".join(meaningful) if meaningful else topic


def ltx_stock_image_query(topic: str, text_or_kw: str) -> str:
    """
    Pexels search for LTX start frames — cinematic B-roll stills, not user portraits.
    Avoids lip-sync oddities from re-using uploaded face photos.
    """
    base = text_or_kw if text_or_kw and _is_mostly_latin(text_or_kw) else topic
    return f"cinematic {base} atmosphere b-roll"


def _is_mostly_latin(text: str) -> bool:
    if not text:
        return True
    latin = sum(1 for c in text if ord(c) < 128)
    return latin / max(len(text), 1) > 0.7


def _keyword_for_scene(
    scene: dict,
    blocks: list[dict],
    english_keywords: list[str] | None,
    topic: str,
) -> str:
    if scene.get("visual_keywords_en"):
        return scene["visual_keywords_en"]
    best_i = 0
    best_overlap = 0.0
    for i, b in enumerate(blocks):
        overlap = min(scene["end_s"], b["end_s"]) - max(scene["start_s"], b["start_s"])
        if overlap > best_overlap:
            best_overlap = overlap
            best_i = i
    if english_keywords and best_i < len(english_keywords):
        return english_keywords[best_i]
    return topic


def merge_short_scenes(scenes: list[dict], topic: str, min_dur: float = MIN_SCENE_S) -> list[dict]:
    if not scenes:
        return scenes
    scenes = sorted(scenes, key=lambda s: s["start_s"])
    out: list[dict] = [dict(scenes[0])]
    for raw in scenes[1:]:
        cur = dict(raw)
        prev = out[-1]
        prev_d = prev["end_s"] - prev["start_s"]
        cur_d = cur["end_s"] - cur["start_s"]
        if cur_d < min_dur or prev_d < min_dur:
            prev["end_s"] = cur["end_s"]
            if cur.get("transcript"):
                prev["transcript"] = f"{prev.get('transcript', '')} {cur['transcript']}".strip()
            prev["narration_hint"] = (prev.get("transcript") or prev.get("narration_hint") or topic)[:120]
            if prev.get("type") == "kenburns" and cur.get("type") != "kenburns":
                prev["type"] = cur["type"]
                prev["source"] = dict(cur.get("source") or prev.get("source") or {})
            kw = cur.get("visual_keywords_en") or prev.get("visual_keywords_en")
            if kw:
                prev["visual_keywords_en"] = kw
        else:
            out.append(cur)
    return [s for s in out if s["end_s"] - s["start_s"] >= 0.5]


def _limit_kenburns_streak(scenes: list[dict], topic: str) -> list[dict]:
    streak = 0
    for scene in scenes:
        if scene.get("type") == "kenburns":
            streak += 1
            if streak > MAX_KENBURNS_STREAK:
                kw = scene.get("visual_keywords_en") or topic
                scene["type"] = "stock"
                scene["source"] = {"query": kw}
                streak = 0
        else:
            streak = 0
    return scenes


def _apply_english_queries(
    scene: dict,
    topic: str,
    blocks: list[dict],
    english_keywords: list[str] | None,
) -> None:
    kw = _keyword_for_scene(scene, blocks, english_keywords, topic)
    scene["visual_keywords_en"] = kw
    src = scene.setdefault("source", {})
    stype = scene.get("type", "stock")
    if stype == "stock":
        src["query"] = kw
    elif stype == "ltx":
        src["stock_image_query"] = ltx_stock_image_query(topic, kw)
        src["prompt"] = (
            f"Slow cinematic camera movement, ambient B-roll, no lip sync. Context: {kw}"
        )
        src.pop("start_image_asset_id", None)


def split_oversized_ltx_scenes(scenes: list[dict], max_s: float = MAX_LTX_SCENE_S) -> list[dict]:
    """Split any LTX scene longer than max_s into LTX head + stock tail."""
    out: list[dict] = []
    for scene in scenes:
        dur = scene["end_s"] - scene["start_s"]
        if scene.get("type") != "ltx" or dur <= max_s + 0.01:
            out.append(dict(scene))
            continue
        head = dict(scene)
        head["end_s"] = round(scene["start_s"] + max_s, 2)
        out.append(head)
        kw = scene.get("visual_keywords_en") or scene.get("narration_hint") or "cinematic broll"
        out.append({
            "id": scene["id"],
            "start_s": head["end_s"],
            "end_s": scene["end_s"],
            "type": "stock",
            "source": {"query": kw},
            "transcript": scene.get("transcript", ""),
            "narration_hint": scene.get("narration_hint", ""),
            "visual_keywords_en": scene.get("visual_keywords_en"),
        })
    for i, scene in enumerate(out, 1):
        scene["id"] = f"s{i}"
    return out


def postprocess_scenes(
    scenes: list[dict],
    topic: str,
    blocks: list[dict],
    english_keywords: list[str] | None,
    total_duration_s: float,
) -> list[dict]:
    scenes = merge_short_scenes(scenes, topic)
    scenes = split_oversized_ltx_scenes(scenes)
    scenes = _limit_kenburns_streak(scenes, topic)
    for scene in scenes:
        _apply_english_queries(scene, topic, blocks, english_keywords)
    _normalize_scene_coverage(scenes, total_duration_s)
    return scenes


def _normalize_scene_coverage(scenes: list[dict], total_duration_s: float):
    if not scenes:
        scenes.append({
            "id": "s1", "start_s": 0, "end_s": total_duration_s,
            "type": "stock", "source": {"query": "cinematic broll"},
            "transcript": "", "narration_hint": "",
        })
        return
    scenes.sort(key=lambda s: s["start_s"])
    if scenes[0]["start_s"] > 0.1:
        scenes[0]["start_s"] = 0
    if scenes[-1]["end_s"] < total_duration_s - 0.5:
        scenes[-1]["end_s"] = round(total_duration_s, 2)


def _enrich_scenes(board: dict, assets: list[dict], total_duration_s: float, aspect_ratio: str, topic: str) -> dict:
    asset_by_id = {a["id"]: a for a in assets}
    scenes_out = []
    for i, raw in enumerate(board.get("scenes", [])):
        scene = dict(raw)
        scene.setdefault("id", f"s{i + 1}")
        scene["start_s"] = round(float(scene.get("start_s", 0)), 2)
        scene["end_s"] = round(float(scene.get("end_s", scene["start_s"] + 5)), 2)
        stype = scene.get("type", "stock")
        scene["type"] = stype
        scene["needs_gpu"] = _needs_gpu(stype)
        preview = _immediate_visual_url(scene, asset_by_id)
        scene["visual_preview_url"] = preview
        scene["start_frame_preview_url"] = None  # filled by attach_preview_urls
        scene["visual_status"] = _visual_status_for_type(stype, preview)
        scene["render_status"] = _render_status_for_type(stype)
        scene["rendered_video_url"] = None
        scene["error"] = None
        if stype == "ltx":
            _sanitize_ltx_source(scene, topic)
        scenes_out.append(scene)

    return {
        "topic": board.get("topic") or topic,
        "master_audio_url": board.get("master_audio_url"),
        "total_duration_s": total_duration_s,
        "aspect_ratio": aspect_ratio,
        "scenes": scenes_out,
    }


def _sanitize_ltx_source(scene: dict, topic: str):
    """Ensure LTX scenes use stock photo queries, not user portrait assets."""
    src = scene.setdefault("source", {})
    kw = scene.get("visual_keywords_en") or topic
    if not src.get("stock_image_query") or not _is_mostly_latin(src.get("stock_image_query", "")):
        src["stock_image_query"] = ltx_stock_image_query(topic, kw)
    src.pop("start_image_asset_id", None)
    if not src.get("prompt") or not _is_mostly_latin(src.get("prompt", "")):
        src["prompt"] = (
            f"Slow cinematic camera movement, ambient B-roll, no lip sync. "
            f"Context: {kw}"
        )


def _immediate_visual_url(scene: dict, asset_by_id: dict) -> str | None:
    stype = scene.get("type", "")
    src = scene.get("source") or {}
    if stype == "ltx":
        return src.get("preview_thumb_url")
    if stype in ("user_image", "screenshot", "kenburns", "user_video"):
        aid = src.get("asset_id")
        if aid and aid in asset_by_id:
            return asset_by_id[aid].get("media_url")
    if stype == "stock":
        return src.get("preview_thumb_url")
    return None


def recompute_scene_previews(storyboard: dict, assets: list[dict]) -> dict:
    """Recompute preview URLs after user edits a scene."""
    asset_by_id = {a["id"]: a for a in assets}
    for scene in storyboard.get("scenes", []):
        stype = scene.get("type", "")
        preview = _immediate_visual_url(scene, asset_by_id)
        scene["visual_preview_url"] = preview
        if scene.get("render_status") != "done":
            scene["visual_status"] = _visual_status_for_type(stype, preview)
            scene["needs_gpu"] = _needs_gpu(stype)
            if stype == "ltx":
                _sanitize_ltx_source(scene, storyboard.get("topic", ""))
            if scene.get("render_status") not in ("generating", "done"):
                scene["render_status"] = _render_status_for_type(stype)
                if stype == "ltx":
                    scene["rendered_video_url"] = None
    return storyboard
